import { useTranslation } from '../i18n/useTranslation';
const copy = {
 pt: [['Encontrar uma prova', 'Pesquisa pelo nome e filtra por data, modalidade ou distrito. Alterna entre lista e calendário.'], ['Consultar o original', 'O nome da prova e “Ver original” abrem a página de origem num novo separador. Confirma lá as inscrições, horários, percursos e eventuais alterações.'], ['Guardar e exportar', 'A estrela guarda a prova nos Favoritos. Podes exportar as datas da lista para um ficheiro .ics; cada entrada inclui a ligação original. Um ficheiro exportado não se atualiza automaticamente e não faz a inscrição.'], ['Minha Agenda', 'A agenda permite consultar marcações anteriormente criadas na conta Google ligada. A criação de novas marcações pela integração e os alertas por email estão suspensos.']],
 en: [['Find an event', 'Search by name and filter by date, discipline or district. Switch between list and calendar.'], ['View the original', 'The event name and “View original” open the source in a new tab. Confirm registration, schedules, routes and changes there.'], ['Save and export', 'The star saves favorites. Export the list as .ics with original links. Downloaded files do not update automatically or register you for a race.'], ['My schedule', 'View entries previously created in your connected Google account. Creating new entries through the integration and email alerts are suspended.']],
 es: [['Encontrar una prueba', 'Busca por nombre y filtra por fecha, modalidad o distrito. Alterna entre lista y calendario.'], ['Ver original', 'El nombre y “Ver original” abren la fuente en otra pestaña. Confirma allí inscripciones, horarios, recorridos y cambios.'], ['Guardar y exportar', 'La estrella guarda favoritos. Exporta la lista como .ics con enlaces originales. Los archivos no se actualizan automáticamente ni realizan la inscripción.'], ['Mi agenda', 'Consulta las entradas anteriores de tu cuenta Google vinculada. Las nuevas entradas mediante la integración y las alertas por email están suspendidas.']],
 fr: [['Trouver une épreuve', 'Recherchez un nom et filtrez par date, discipline ou district. Alternez liste et calendrier.'], ['Voir l’original', 'Le nom et « Voir l’original » ouvrent la source dans un nouvel onglet. Confirmez les inscriptions, horaires, parcours et changements sur place.'], ['Enregistrer et exporter', 'L’étoile enregistre les favoris. Exportez la liste au format .ics avec les liens originaux. Les fichiers ne se mettent pas à jour automatiquement et ne vous inscrivent pas.'], ['Mon agenda', 'Consultez les anciennes entrées de votre compte Google lié. Les nouvelles entrées via l’intégration et les alertes par email sont suspendues.']],
};
export default function PlanningHelp() {
 const { language } = useTranslation();
 return <div className="grid gap-3 mb-8">{(copy[language] || copy.pt).map(([title, body]) => <section key={title} className="border border-line bg-surface rounded p-4"><h2 className="text-base font-bold text-ink mb-2">{title}</h2><p className="text-sm text-muted leading-relaxed">{body}</p></section>)}</div>;
}
